### ISSUE TITLE
Several Issues with Wiki, Data-Collection and Learning Module

### ISSUE THREAD

**Issue by Amstutz** [colin-kiegel/ilias-hhvm#3]
White pages appear in the mentioned modules. Those issues are probably all related to the page editor. 

See examples in the following course:
https://sigperf-hhvm.iliasnet.de/goto.php?target=crs_215&client_id=SIGPERF

**Comment by colin-kiegel** [comment]
page editor works in trunk. Further issues should be reported in the ilias bug tracker.
